### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by Lunavast** [bld3r/bld3r#4]
Is there any installation instruction for bld3r?

**Comment by scoofy** [comment]
There is no installation necessary. It runs on AppEngine, and can be launched in the AppEngine launcher trivially easily, there are a few variable to change depending on your site name and URL. All of these are fairly straight forward in the file. The data folder holds the basic editable site-specific content (approx 3 variables), the do not copy folder has is where you implement a hash that your cookies' security is based on.
